# Generated by Django 4.2.5 on 2023-09-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
